### DISCUSSION TITLE
docker-compose.yml for mempool

### DISCUSSION THREAD

**Discussion by N8schrath** [shinebayar-g/ufw-docker-automated#50] [Q&A]
I'm asking for help rather than raising an issue.

I'm running my own mempool instance with docker-compose, as shown on [github.com/mempool/mempool](https://github.com/mempool/mempool) and [github.com/mempool/mempool/tree/master/docker](https://github.com/mempool/mempool/tree/master/docker). If UFW is disabled everything works as expected, but with UFW enabled the known issues occur. I installed and prepared everything along your instructions, but the problem is I don't know which edits I have to make in "docker-compose.yml", because I know way to little to do this on my own even with the examples you showed.
This is the file:

```
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080

  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "10.0.0.9"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "10.0.0.9"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "myusername"
      CORE_RPC_PASSWORD: "mypassword"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
```
I understand that I have to add something like this:
```
    labels:
      UFW_MANAGED: 'TRUE'
      UFW_ALLOW_FROM: '172.10.50.32;192.168.3.0/24;10.10.0.50/32-8080-LAN'
      UFW_DENY_OUT: 'TRUE'
      UFW_ALLOW_TO: '8.8.8.8-53-GoogleDNS;1.1.1.0/24-53-CloudflareDNS;192.168.10.24-8080-LAN'
    networks:
      - my-network
```
But I don't know  in which way I have to edit the values from the example to fit to my "docker-compose.yml"-File.

**Comment by shinebayar-g** [comment]
Hi. What exactly are you trying to accomplish?
I see you have
```yml
    ports:
      - 4080:8080
```
for your `web:` service. Do you want to protect this container with ufw?
If that's the case you add the `labels` to your `web:` service. Looks like other containers don't need any ufw labels because they don't have any `ports` published.

**Reply by N8schrath** [reply]
Hello shinebayar-g, thanks for answering and I'm sorry for posting this topic in the wrong place. :see_no_evil: 

The instance of mempool ist openend on a webbrowser on http://127.0.0.1:4080 and I want it to work without having to disable ufw.
If I run the container with ufw enabled the container-log gives the following error:
`docker-api-1 [99] INFO: Disconnected from Electrum Server at 10.0.0.9:50002`
So the problem is ufw blocks docker from connecting to my electrum server. I'm running everything on the same machine (bitcoin core, electrum server and docker).

Which labels do I have to add to my `web:` service so that ufw stops blocking docker from connecting with the electrum server?

**Reply by shinebayar-g** [reply]
Okay. I understand that you're trying to open `web` service to your browser? In that case you have a few options.
1. If you don't have to open `web` service externally. For example only localhost is fine, then you don't need ufw at all. Just do
```
ports:
      - 127.0.0.1:4080:8080
```
This makes container's `8080` port available to your `localhost:4080` or `127.0.0.1:4080`

2. If you need to open `web` service externally, for example both to localhost and other containers in the same docker compose network: You'll need same ports defined as step 1. But containers in the same network should refer each other by its name. like `web:8080`, `api:50002` etc. You most likely won't need ufw at all in this scenario. Unless you want to be really restricted. Bonus point: Make sure how your browser is supposed to connect to each service. For example, if it needs to connect to both `web` and `api` in that case you have to publish ports on both etc.

3. If you need to open your containers externally beyond your localhost and docker compose network, for example to another container in the different network or another device in your LAN network or even Direct Internet connection etc.. Then you can make use of ufw.
For example, assuming you're going to open `web` and `api` to some random IP address on your network. Then the syntax would be:

```yaml
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080
    # By adding these labels you're adding ufw rules that allow connections from the specified IP addresses to this specific container.
    # check ufw rules after starting the container with: sudo ufw status
    # Notice that you're specifying the port of the container, not the host port.
    labels:
      UFW_MANAGED: 'TRUE'
      UFW_ALLOW_FROM: '192.168.50.132-8080-SomeRandomDeviceOnYourLan;192.168.0.0/24-OrYourEntireLan'

  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "10.0.0.9"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "10.0.0.9"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "myusername"
      CORE_RPC_PASSWORD: "mypassword"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache

  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
```
