### ISSUE TITLE
ufw-docker-automated in docker-compose

### ISSUE THREAD

**Issue by vedrancek** [shinebayar-g/ufw-docker-automated#1]
Hello,

this not an issue report but a question.
How to implement your feature with docker compose?

Cheers!

**Comment by shinebayar-g** [comment]
Hi @vedrancek , thanks for checking out my project. It should work with following sample. But it's not working. I'll dig further the issue and will give feedback.

```yaml
version: "2.1"
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:80"
    labels:
        UFW_MANAGED: "TRUE"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
```
