### ISSUE TITLE
docker-compose.yml for mempool

### ISSUE THREAD

**Issue by N8schrath** [shinebayar-g/ufw-docker-automated#49]
I'm asking for help rather than raising an issue.

I'm running my own mempool instance with docker-compose, as shown on [github.com/mempool/mempool](https://github.com/mempool/mempool) and [github.com/mempool/mempool/tree/master/docker](https://github.com/mempool/mempool/tree/master/docker). If UFW is disabled everything works as expected, but with UFW enabled the known issues occur. I installed and prepared everything along your instructions, but the problem is I don't know which edits I have to make in "docker-compose.yml", because I know way to little to do this on my own even with the examples you showed.
This is the file:

```
version: "3.7"

services:
  web:
    environment:
      FRONTEND_HTTP_PORT: "8080"
      BACKEND_MAINNET_HTTP_HOST: "api"
    image: mempool/frontend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for db:3306 --timeout=720 -- nginx -g 'daemon off;'"
    ports:
      - 4080:8080

  api:
    environment:
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "10.0.0.9"
      ELECTRUM_PORT: "50002"
      ELECTRUM_TLS_ENABLED: "true"
      CORE_RPC_HOST: "10.0.0.9"
      CORE_RPC_PORT: "8332"
      CORE_RPC_USERNAME: "myusername"
      CORE_RPC_PASSWORD: "mypassword"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    image: mempool/backend:latest
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    command: "./wait-for-it.sh db:3306 --timeout=720 --strict -- ./start.sh"
    volumes:
      - ./data:/backend/cache
  db:
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
    image: mariadb:10.5.8
    user: "1000:1000"
    restart: always
    stop_grace_period: 1m
    volumes:
      - ./mysql/data:/var/lib/mysql
```
I understand that I have to add something like this:
```
    labels:
      UFW_MANAGED: 'TRUE'
      UFW_ALLOW_FROM: '172.10.50.32;192.168.3.0/24;10.10.0.50/32-8080-LAN'
      UFW_DENY_OUT: 'TRUE'
      UFW_ALLOW_TO: '8.8.8.8-53-GoogleDNS;1.1.1.0/24-53-CloudflareDNS;192.168.10.24-8080-LAN'
    networks:
      - my-network
```
But I don't know  in which way I have to edit the values from the example to fit to my "docker-compose.yml"-File.
