### ISSUE TITLE
Problems accessing port

### ISSUE THREAD

**Issue by exander77** [shinebayar-g/ufw-docker-automated#63]
```
    ports:
      - ip:21:21
      - ip:21000-21010:21000-21010
    labels:
      UFW_MANAGED: 'TRUE'
      UFW_ALLOW_FROM: '0.0.0.0-21;0.0.0.0-21000;0.0.0.0-21001;0.0.0.0-21002;0.0.0.0-21003;0.0.0.0-21004;0.0.0.0-21005;0.0.0.0-21006;0.0.0.0-21007;0.0.0.0-21008;0.0.0.0-21009;0.0.0.0-21010'
```

```
172.25.0.2 21/tcp          ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21000/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21001/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21002/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21003/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21004/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21005/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21006/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21007/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21008/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21009/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
172.25.0.2 21010/tcp       ALLOW FWD   0.0.0.0                    # ftp-ftp-1:b4f6104135df
```

```
May 21 00:38:53 server kernel: [6740192.662607] [UFW DOCKER BLOCK] IN=ens18 OUT=br-a4b2272b5f4e MAC=36:24:05:bc:0f:f4:d6:42:5c:89:88:91:08:00 SRC=109.248.251.200 DST=172.25.0.2 LEN=60 TOS=0x10 PREC=0x00 TTL=63 ID=57620 DF PROTO=TCP SPT=59112 DPT=21 WINDOW=64240 RES=0x00 SYN URGP=0 
```

I cannot connect from outside the server (can connet from the server):
```
telnet ip 21
```

**Comment by kevinf100** [comment]
Little late, but it's 0.0.0.0/0 for any. UFW is looking for IP 0.0.0.0 as the default CIDR notion is 0.0.0.0/32 when not defined.
```
    ports:
      - ip:21:21
      - ip:21000-21010:21000-21010
    labels:
      UFW_MANAGED: 'TRUE'
      UFW_ALLOW_FROM: '0.0.0.0/0-21;0.0.0.0/0-21000;0.0.0.0/0-21001;0.0.0.0/0-21002;0.0.0.0/0-21003;0.0.0.0/0-21004;0.0.0.0/0-21005;0.0.0.0/0-21006;0.0.0.0/0-21007;0.0.0.0/0-21008;0.0.0.0/0-21009;0.0.0.0/0-21010'
```
